const data  = {
    produtos: [
      {         
        id: '1',
        descricao: 'ALION',
        unidade: 'L',
        volume: 1,
        marca: 'BAYER',
        peso: '1.1KG',        
        quantidade: 10,
        preco: 59.90,   
        index: 0,
      },
      {         
        id: '2',
        descricao: 'VIR CONTROL',
        unidade: 'KG',
        volume: 5,
        marca: 'SIMBIOSE',
        peso: '5.01KG',  
        quantidade: 2,
        preco: 99.90,      
        index: 2,        
      },
      {         
        id: '3',
        descricao: 'CURZATE',
        unidade: 'GL',
        volume: 5,
        marca: 'CORTEVA',
        peso: '5.01KG',
        quantidade: 5,
        preco: 78.95,        
        index: 1,        
      },
      {         
        id: '4',
        descricao: 'DMA',
        unidade: 'L',
        volume: 1,
        marca: 'CORTEVA',
        peso: '1.03KG',   
        quantidade: 2,
        preco: 129.90,     
        index: 3,        
      },    
     
    ],
};
export default data;